"""
vectorizer.py
-------------
TF-IDF vectorization and compact document embeddings.
"""

from typing import Optional, Tuple

import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import Normalizer


class TextVectorizer:
    """
    Convert cleaned review text into model-ready features.

    TF-IDF is used as the sparse baseline representation. Optional embeddings are
    generated by applying TruncatedSVD to TF-IDF, which gives dense semantic
    document vectors without requiring external model downloads.
    """

    def __init__(
        self,
        max_features: int = 5000,
        ngram_range: Tuple[int, int] = (1, 2),
        min_df: int = 2,
        max_df: float = 0.9,
        embedding_dim: int = 100,
    ):
        self.max_features = max_features
        self.ngram_range = ngram_range
        self.min_df = min_df
        self.max_df = max_df
        self.embedding_dim = embedding_dim

        self.tfidf = TfidfVectorizer(
            max_features=max_features,
            ngram_range=ngram_range,
            min_df=min_df,
            max_df=max_df,
            lowercase=False,
        )
        self.svd: Optional[TruncatedSVD] = None
        self.normalizer = Normalizer(copy=False)

    def fit_transform_tfidf(self, texts) -> sparse.csr_matrix:
        """Fit the TF-IDF vectorizer and return a sparse matrix."""
        text_list = self._as_text_list(texts)
        if not text_list:
            raise ValueError("Cannot vectorize an empty text collection.")

        self.tfidf = self._new_tfidf_vectorizer(len(text_list))
        return self.tfidf.fit_transform(text_list)

    def transform_tfidf(self, texts) -> sparse.csr_matrix:
        """Transform new texts with an already fitted TF-IDF vectorizer."""
        return self.tfidf.transform(self._as_text_list(texts))

    def fit_transform_embeddings(self, texts) -> np.ndarray:
        """Fit TF-IDF + SVD and return dense document embeddings."""
        tfidf_matrix = self.fit_transform_tfidf(texts)
        # SVD compresses sparse TF-IDF into dense semantic vectors.
        return self._fit_embeddings_from_tfidf(tfidf_matrix)

    def transform_embeddings(self, texts) -> np.ndarray:
        """Transform new texts into dense embeddings."""
        tfidf_matrix = self.transform_tfidf(texts)
        if self.svd is None:
            return self.normalizer.transform(tfidf_matrix.toarray())

        embeddings = self.svd.transform(tfidf_matrix)
        return self.normalizer.transform(embeddings)

    def build_feature_frame(
        self,
        df: pd.DataFrame,
        text_col: str = "token_text",
        include_embeddings: bool = True,
    ) -> Tuple[pd.DataFrame, sparse.csr_matrix, Optional[np.ndarray]]:
        """
        Return a copy of df with embedding columns plus raw feature matrices.
        """
        if text_col not in df.columns:
            raise ValueError(f"Column '{text_col}' not found.")

        feature_df = df.copy()
        tfidf_matrix = self.fit_transform_tfidf(feature_df[text_col])
        embeddings = None

        if include_embeddings:
            embeddings = self._fit_embeddings_from_tfidf(tfidf_matrix)

            for idx in range(embeddings.shape[1]):
                feature_df[f"embedding_{idx + 1:03d}"] = embeddings[:, idx]

        return feature_df, tfidf_matrix, embeddings

    def get_feature_names(self) -> list:
        """Return TF-IDF vocabulary terms."""
        return self.tfidf.get_feature_names_out().tolist()

    @staticmethod
    def _as_text_list(texts) -> list:
        if isinstance(texts, pd.Series):
            return texts.fillna("").astype(str).tolist()
        return ["" if text is None else str(text) for text in texts]

    def _new_tfidf_vectorizer(self, doc_count: int) -> TfidfVectorizer:
        max_df = 1.0 if doc_count < 2 else self.max_df
        return TfidfVectorizer(
            max_features=self.max_features,
            ngram_range=self.ngram_range,
            min_df=self.min_df,
            max_df=max_df,
            lowercase=False,
        )

    def _fit_embeddings_from_tfidf(self, tfidf_matrix: sparse.csr_matrix) -> np.ndarray:
        n_docs, n_features = tfidf_matrix.shape
        if n_docs == 0 or n_features == 0:
            raise ValueError("Cannot build embeddings from an empty TF-IDF matrix.")

        if n_docs < 2 or n_features < 2:
            # Skip SVD on tiny corpora; normalize dense TF-IDF instead.
            self.svd = None
            dense = tfidf_matrix.toarray()
            return self.normalizer.fit_transform(dense)

        n_components = min(self.embedding_dim, n_features - 1)
        self.svd = TruncatedSVD(n_components=n_components, random_state=42)
        embeddings = self.svd.fit_transform(tfidf_matrix)
        return self.normalizer.fit_transform(embeddings)
